stages:
- name: build-stage
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: docker-registry-build-demo
      pushRemote: true
      registry: 116.85.13.70
timeout: 60
