stages:
- name: build-stage
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: docker-registry-build-demo
      pushRemote: true
      registry: quay.io
timeout: 60
